echo "---build start---"

node {
    stage('Clone') {
        echo '>>> Git repository Clone'
        git branch: 'main', credentialsId: 'qawesdxc@naver.com' , url: "https://github.com/Oh-JunYoung/CowAPI-Front.git"
    }

    stage('Move to Path') {
        echo '>>> Move to Deploy Path'
        sudo sh './jenkins/MovePath.sh'
    }

    stage('Pull') {
        echo '>>> Git repository Clone'
        sudo sh './jenkins/GitPull.sh'
    }

    stage('Build') {
        echo '>>> Gradle project Build'
        sudo sh './jenkins/Build.sh'
    }

    stage('Nginx') {
        echo '>>> Gradle project Deploy'
        sudo sh './jenkins/Nginx.sh'
    }
}