echo "---build start---"

node {
    stage('Clone') {
        echo '>>> Git repository Clone'
        git branch: 'feature/Jenkins', credentialsId: '6b0913f3-9133-41d9-bbf1-1c0baaafb86b' , url: "git@github.com:Oh-JunYoung/CowAPI-Front.git"
    }

    stage('Move to Path') {
        echo '>>> Move to Deploy Path'
        sh './jenkins/MovePath.sh'
    }

    stage('Pull') {
        echo '>>> Git repository Clone'
        sh './jenkins/GitPull.sh'
    }

    stage('Intall npm') {
        echo '>>> npm install start'
        sh './jenkins/NpmInstall.sh'
    }

    stage('Build') {
        echo '>>> Gradle project Build'
        sh './jenkins/Build.sh'
    }

    stage('Nginx') {
        echo '>>> Gradle project Deploy'
        sh './jenkins/Nginx.sh'
    }
}